# Generated by Django 4.2.4 on 2023-08-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departments_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName',
        ),
    ]
